modify cicd

diff --git a/.github/workflows/github-actions-ec2.yml b/.github/workflows/github-actions-ec2.yml
--- a/.github/workflows/github-actions-ec2.yml
+++ b/.github/workflows/github-actions-ec2.yml
@@ -36,7 +36,14 @@ jobs:
         run: |
           ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd ${{ secrets.TARGET_DIR }} && curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt install -y nodejs && npm install"
       
-      - name: Start the app on EC2
+      - name: Start the app on EC2 in background
         run: |
-          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd ${{ secrets.TARGET_DIR }} && npm run serve"
-      
+          ssh -i "path_to_your_private_key.pem" -o StrictHostKeyChecking=no username@your_ec2_host "cd your_project_directory && nohup npm run serve > server.log 2>&1 &"
+      - name: Post Checkout the files
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://54.91.10.155:3000/)
+          if [ "$response" -ne 200 ]; then
+            echo "Server check failed with HTTP code: $response"
+            exit 1
+          fi
+        
